after-login-command = []

# exec-on-workspace-change = ['/bin/bash', '-c',
#     'sketchybar --trigger aerospace_workspace_change'
# ]
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 2
inner.vertical =   2
outer.left =       2
outer.bottom =     2
outer.top =        2
outer.right =      2

[mode.main.binding]

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-b = 'workspace B'
alt-t = 'workspace T'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-t = 'move-node-to-workspace T'
alt-s = ['exec-and-forget ~/dotfiles/binaries/run_spotify', 'mode main']

alt-shift-f = 'fullscreen'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-n = 'mode service'

alt-f = 'mode focused'

alt-m = 'mode launch'


[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']
shift-f = ['mode main', 'macos-native-fullscreen']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[mode.focused.binding]
alt-f = 'mode main'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

[mode.launch.binding]
alt-m = 'mode main'
b = ['exec-and-forget open /Applications/LibreWolf.app/', 'mode main']
shift-b = ['exec-and-forget open /Applications/Chromium.app/', 'mode main']
t = ['exec-and-forget open /Applications/Ghostty.app/', 'mode main']
s = ['exec-and-forget open /Applications/Spotify.app/', 'mode main']
q = ['exec-and-forget open /Applications/qbittorrent.app/', 'mode main']
j = ['exec-and-forget open /Applications/Jellyfin.app/', 'mode main']
p = ['exec-and-forget open /Applications/Plex Media Server.app/', 'mode main']
d = ['exec-and-forget open /Applications/Discord.app/', 'mode main']
shift-s = ['exec-and-forget open /Applications/Stremio.app/', 'mode main']
esc = 'mode main'
f = ['exec-and-forget open /Applications/FreeTube.app/', 'mode main']
k = ['exec-and-forget ~/dotfiles/binaries/run_spotify', 'mode main']


[[on-window-detected]]
if.app-id = 'net.java.openjdk.java'
run = ['layout floating']
